# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acf469bee58cf9fb2183a48fcf17cf0138f80b0633cbfb4223a4d9934e9d31cb63be12974bc72efd626a107878786625fe8515a247ac55f9a6312a5ca92a4247

test:
  secret_key_base: 0208bbb0e44a109b608c2f5a4a037916b1bd7ba2c4077e87f15fedba201bfd9112b1ce6384052300a4c4c6f4be975a7239babde552a9fa8dab68b2b155673223

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
